name: Run API Tests and Publish Dashboard

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Acción oficial de Postman CLI
      - name: Run Postman CLI
        uses: postmanlabs/postman-cli-action@v1
        with:
          api_key: ${{ secrets.POSTMAN_API_KEY }}   # tu API Key de Postman
          collection: coleccion.json                # tu colección exportada
          environment: environment.json             # tu environment exportado
          reporters: cli,html                       # reporters que quieres usar
          reporter_html_export: reporte.html        # archivo HTML generado

      # Subir el reporte como artefacto descargable
      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: postman-dashboard
          path: reporte.html

      # Publicar el dashboard en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          keep_files: true
          allow_empty_commit: true
