name: Run API Tests and Publish Dashboard

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Postman CLI
        run: npm install postman-cli

      - name: Run Postman tests
        run: |
          npx postman-cli collection run collection.json \
            -e environment.json \
            --env-var "key=${{ secrets.KEY }}" \
            --env-var "token=${{ secrets.TOKEN }}" \
            --reporters cli,html \
            --reporter-html-export reporte.html

      - name: Prepare report for Pages
        run: |
          mkdir -p public
          mv reporte.html public/index.html

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: postman-dashboard
          path: public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
